/**
 * The preservation sequence.
 *
 * The generated plan, and — more importantly — the reasoning. A numbered list
 * would be a black box with a veneer of authority on it. Every step here
 * carries four things: why it is where it is, what is at risk if it moves,
 * which step it exists to precede, and what stops existing after it.
 *
 * The gates are drawn as headings rather than left implicit, because "these
 * four captures must all happen before the restart" is the shape of the
 * argument, and a flat list hides it.
 */

import { useMemo } from 'react'
import type { AnalysisResult, SequenceStep } from '../domain/types.ts'
import { formatDuration } from '../domain/time.ts'
import { FOCUS, LABEL, PANEL_INSET } from '../ui/tokens.ts'
import {
  Button,
  Callout,
  ConfidenceMeter,
  Empty,
  Panel,
  PanelHeader,
  cx,
} from '../ui/primitives.tsx'
import type { ViewId } from '../state.ts'

export function SequenceView({
  result,
  onAdopt,
  onSelectStep,
  onSelectArtifact,
  onNavigate,
}: {
  result: AnalysisResult
  onAdopt: (order: readonly string[]) => void
  onSelectStep: (id: string) => void
  onSelectArtifact: (id: string) => void
  onNavigate: (v: ViewId) => void
}) {
  const { sequence, feasibility } = result
  const byId = useMemo(
    () => new Map(result.artifacts.map((a) => [a.artifact_id, a])),
    [result.artifacts],
  )

  const improvement = useMemo(() => {
    const badness = {
      preserved: 0,
      retained: 1,
      degraded: 2,
      indeterminate: 3,
      accepted_loss: 4,
      lost: 5,
    } as const
    const rec = new Map(result.recommended_outcomes.map((o) => [o.artifact_id, o]))
    return result.outcomes.filter((o) => {
      const r = rec.get(o.artifact_id)
      return r !== undefined && badness[o.outcome] > badness[r.outcome]
    })
  }, [result])

  if (sequence.steps.length === 0) {
    return (
      <Panel>
        <Empty title="Nothing to sequence">
          This plan has no steps. Add some in the remediation plan view, or load a demo scenario.
        </Empty>
      </Panel>
    )
  }

  return (
    <div className="space-y-5">
      {sequence.matches_plan_order ? (
        <Callout tone="good" title="The plan is already in this order">
          Nothing needs to move. The sequence below is what you wrote, with the reasoning for each
          position spelled out.
        </Callout>
      ) : (
        <Callout tone="warn" title="This is not the order the plan is currently in">
          <p>
            Same steps, same remediation, different order.{' '}
            {improvement.length === 0 ? (
              <>No artifact changes outcome, so this is a preference rather than a finding.</>
            ) : (
              <>
                {improvement.length}{' '}
                {improvement.length === 1 ? 'artifact ends' : 'artifacts end'} up better under this
                order — preserved rather than lost, or intact rather than altered:{' '}
                <span className="text-ink-0">{improvement.map((o) => o.name).join(', ')}</span>.
              </>
            )}
          </p>
          <div className="mt-2.5 flex flex-wrap gap-2">
            <Button size="sm" variant="primary" onClick={() => onAdopt(sequence.order)}>
              Adopt this order
            </Button>
            <Button size="sm" variant="quiet" onClick={() => onNavigate('plan')}>
              Edit the plan instead
            </Button>
          </div>
        </Callout>
      )}

      <Panel>
        <PanelHeader
          title="Recommended order"
          hint="Generated by a deterministic rule, not by a model. Captures are placed relative to the steps that threaten what they collect; the remediation keeps the relative order you gave it, because its dependencies are not something this tool can see."
          right={
            <span className="tnum text-xs text-ink-3">
              {formatDuration(feasibility.preservation_minutes + feasibility.remediation_minutes)}{' '}
              of steps
            </span>
          }
        />

        <ol>
          {sequence.steps.map((s, i) => {
            const prev = i > 0 ? sequence.steps[i - 1] : undefined
            const gateStarts = s.gate !== null && prev?.gate !== s.gate
            const gate = s.gate === null ? undefined : sequence.gates.find((g) => g.gate === s.gate)
            return (
              <li key={s.step_id}>
                {gateStarts && gate ? (
                  <div className="border-y border-line-1 bg-surface-2 px-5 py-2.5">
                    <p className={cx(LABEL, 'text-accent')}>
                      Preservation gate {gate.gate + 1} — before "{gate.before_action_name}"
                    </p>
                    <p className="mt-1 max-w-[84ch] text-xs leading-relaxed text-ink-2">
                      {gate.reason}
                    </p>
                  </div>
                ) : null}
                <SequenceRow
                  step={s}
                  names={s.artifact_ids
                    .map((id) => byId.get(id)?.name)
                    .filter((x): x is string => x !== undefined)}
                  onSelectStep={onSelectStep}
                  onSelectArtifact={(name) => {
                    const a = result.artifacts.find((x) => x.name === name)
                    if (a) onSelectArtifact(a.artifact_id)
                  }}
                />
              </li>
            )
          })}
        </ol>

        <div className="border-t border-line-1 px-5 py-4">
          <p className="max-w-[84ch] text-2xs leading-relaxed text-ink-3">
            Within a gate, the order is: most volatile first by the volatility ladder, then
            collection priority, then the shorter capture, then the action id so the output is
            stable. Captures covering volatile evidence are pulled to the front regardless of what
            the plan threatens, because connections close and processes exit without anybody's
            help — a capture taken twenty minutes later is a capture of something else.
          </p>
        </div>
      </Panel>

      {/* ---- gates summary ------------------------------------------------ */}
      {sequence.gates.length > 0 ? (
        <Panel>
          <PanelHeader
            title={`${sequence.gates.length} preservation ${sequence.gates.length === 1 ? 'gate' : 'gates'}`}
            hint="Each gate is a point past which a specific set of evidence no longer exists. This is the part of the sequence that is not negotiable without accepting a loss."
          />
          <ul>
            {sequence.gates.map((g) => (
              <li key={g.gate} className="border-b border-line-1 px-5 py-4 last:border-0">
                <p className="flex flex-wrap items-baseline gap-2">
                  <span className="tnum font-mono text-2xs text-ink-3">Gate {g.gate + 1}</span>
                  <span className="text-sm font-medium text-ink-0">
                    before "{g.before_action_name}"
                  </span>
                </p>
                <div className="mt-2 flex flex-wrap gap-1.5">
                  {[...new Set(g.artifact_ids)].map((id) => (
                    <button
                      key={id}
                      type="button"
                      onClick={() => onSelectArtifact(id)}
                      className={cx(
                        PANEL_INSET,
                        'px-2 py-0.5 text-2xs text-ink-2 transition-colors duration-140 hover:text-ink-0',
                        FOCUS,
                      )}
                    >
                      {byId.get(id)?.name ?? id}
                    </button>
                  ))}
                </div>
              </li>
            ))}
          </ul>
        </Panel>
      ) : null}
    </div>
  )
}

function SequenceRow({
  step,
  names,
  onSelectStep,
  onSelectArtifact,
}: {
  step: SequenceStep
  names: readonly string[]
  onSelectStep: (id: string) => void
  onSelectArtifact: (name: string) => void
}) {
  const isCapture = step.kind === 'capture'
  return (
    <div className="flex items-start gap-4 border-b border-line-1 px-5 py-4 transition-colors duration-140 last:border-0 hover:bg-surface-2">
      <div className="flex w-10 shrink-0 flex-col items-center">
        <span
          className={cx(
            'tnum flex h-7 w-7 items-center justify-center rounded-full border font-mono text-xs',
            isCapture
              ? 'border-preserved/50 bg-preserved/10 text-preserved'
              : step.lost_after.length > 0
                ? 'border-lost/50 bg-lost/10 text-lost'
                : 'border-line-2 bg-surface-2 text-ink-2',
          )}
        >
          {String(step.order).padStart(2, '0')}
        </span>
        {step.offset_minutes !== null ? (
          <span className="tnum mt-1.5 font-mono text-2xs text-ink-3">
            +{formatDuration(step.offset_minutes)}
          </span>
        ) : (
          <span className="mt-1.5 text-2xs text-degraded" title="Untimed step: the clock stops here">
            +?
          </span>
        )}
      </div>

      <div className="min-w-0 flex-1">
        <button
          type="button"
          onClick={() => onSelectStep(step.step_id)}
          className={cx('block w-full text-left', FOCUS)}
        >
          <span className="flex flex-wrap items-center gap-2">
            <span className="text-sm font-medium text-ink-0">{step.name}</span>
            <span
              className={cx(
                'rounded border px-1.5 py-0.5 text-2xs font-semibold uppercase tracking-[0.08em]',
                isCapture
                  ? 'border-preserved/35 bg-preserved/10 text-preserved'
                  : 'border-line-2 bg-surface-2 text-ink-3',
              )}
            >
              {isCapture ? 'Capture' : 'Remediation'}
            </span>
            <span className="tnum text-2xs text-ink-3">
              {formatDuration(step.estimated_minutes)}
            </span>
          </span>
        </button>

        <div className="mt-2 space-y-1.5">
          <Reason label="Why now">{step.why_now}</Reason>

          {names.length > 0 ? (
            <Reason label="At risk">
              <span className="inline-flex flex-wrap gap-x-1.5">
                {names.map((n, i) => (
                  <span key={n}>
                    <button
                      type="button"
                      onClick={() => onSelectArtifact(n)}
                      className={cx('underline decoration-line-3 underline-offset-2 hover:text-ink-0', FOCUS)}
                    >
                      {n}
                    </button>
                    {i < names.length - 1 ? ',' : ''}
                  </span>
                ))}
              </span>
            </Reason>
          ) : null}

          {step.enables ? (
            <Reason label="Runs before">{step.enables}</Reason>
          ) : null}

          {step.lost_after.length > 0 ? (
            <Reason label="Lost after" tone="text-lost">
              {step.lost_after.join(', ')}
            </Reason>
          ) : null}
        </div>
      </div>

      <div className="hidden shrink-0 sm:block">
        <ConfidenceMeter confidence={step.confidence} />
      </div>
    </div>
  )
}

function Reason({
  label,
  children,
  tone,
}: {
  label: string
  children: React.ReactNode
  tone?: string
}) {
  return (
    <p className="grid grid-cols-[5.5rem_1fr] gap-x-3 text-xs leading-relaxed">
      <span className={cx(LABEL, 'pt-px')}>{label}</span>
      <span className={cx('min-w-0', tone ?? 'text-ink-2')}>{children}</span>
    </p>
  )
}
